#! /usr/bin/env python
#
# Support module generated by PAGE version 4.10

import sqlite3
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

# Connect to database
connection = sqlite3.connect("data.db")
cursor = connection.cursor()

search = False
results = []
index = 0


def delete_button(p1):
    global index, results

    if 0 <= index < len(results):
        note_id = results[index][0]
        cursor.execute("DELETE FROM notes WHERE id = ?", (note_id,))
        connection.commit()


def create_button(p1):
    try:
        cursor.execute(
            """
            CREATE TABLE notes (
                id INTEGER PRIMARY KEY,
                title TEXT,
                note TEXT
            );
            """
        )
        connection.commit()
        w.errorOutput.configure(text="")
    except sqlite3.OperationalError:
        w.errorOutput.configure(text="The database already exists")


def add_button(p1):
    title = w.inputTitle.get()
    note = w.inputNotice.get(1.0, END)

    if len(title) > 0 and len(note.strip()) > 0:
        try:
            cursor.execute(
                "INSERT INTO notes (title, note) VALUES (?, ?)",
                (title, note),
            )
            connection.commit()
            w.errorOutput.configure(text="")
        except Exception as e:
            w.errorOutput.configure(text=str(e))
    else:
        w.errorOutput.configure(text="Please fill the fields.")


def back_button(p1):
    global index

    w.errorOutput.configure(text="")
    index -= 1

    if 0 <= index < len(results):
        w.outputNotice.delete(1.0, END)
        w.outputNotice.insert(1.0, results[index][2])


def clear_button(p1):
    w.inputNotice.delete(1.0, END)


def exit_button(p1):
    sys.exit(0)


def search_button(p1):
    global results, index

    w.errorOutput.configure(text="")
    search_title = w.inputSearchTitle.get()

    try:
        cursor.execute(
            "SELECT * FROM notes WHERE title LIKE ?",
            (f"%{search_title}%",),
        )
        results = cursor.fetchall()
        w.errorOutput.configure(text=f"{len(results)} results")

        index = 0
        if 0 <= index < len(results):
            w.outputNotice.delete(1.0, END)
            w.outputNotice.insert(1.0, results[index][2])

    except sqlite3.OperationalError:
        w.errorOutput.configure(text="Please create the database first.")


def next_button(p1):
    global index

    index += 1

    if len(w.inputSearchTitle.get()) > 0:
        if 0 <= index < len(results):
            w.outputNotice.delete(1.0, END)
            w.outputNotice.insert(1.0, results[index][2])
    else:
        w.errorOutput.configure(text="Please fill the search field.")


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == "__main__":
    import notepad
    notepad.vp_start_gui()
